### PR TITLE
authentication using passportjs fully implemented

### PR DESCRIPTION
**Pull request by ta4kazzz**

### CODE REVIEW

**Comment by source** [comment]
@ta4kazzz I am getting the following error from running server.js
```
The magic happens on port 8080

/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                        ^
MongoError: auth fails
    at Function.MongoError.create (/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:763:66
    at Callbacks.emit (/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```

and this error from mongo
```
Fri Oct 23 17:06:27.315 [conn21] auth: couldn't find user localuser@source, source.system.users
Fri Oct 23 17:06:27.315 [conn22]  authenticate db: source { authenticate: 1, user: "localuser", nonce: "976134d3c6dcf94a", key: "dd27985f93c506068fafbce130c86a75" }
Fri Oct 23 17:06:27.315 [conn23]  authenticate db: source { authenticate: 1, user: "localuser", nonce: "33acfe74d59087a1", key: "bff0a7d70c838bb98249e0aa3f6c36ec" }
Fri Oct 23 17:06:27.315 [conn22] auth: couldn't find user localuser@source, source.system.users
Fri Oct 23 17:06:27.315 [conn23] auth: couldn't find user localuser@source, source.system.users
```

Any idea on how to fix this? I would like to pull this in and test it as soon as possible

**Comment by ta4kazzz** [comment]
OK I figured it out:
On my local db I have added a user called localuser with pass 123456, in
order to strengthen security.

So to fix this on the source db add a user called local user or try going
to config file on server and remove the user and password. Hopefully it
will revert to default without user loging in to mongo.

For local mongo I am using desktop app called chefmongo(free) it allows
right clicking and adding users to db, much simpler than console.

On Fri, Oct 23, 2015 at 11:08 PM, Source Team <notifications@github.com>
wrote:

> @ta4kazzz <https://github.com/ta4kazzz> I am getting the following error
> from running server.js
>
> The magic happens on port 8080
>
> /Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/lib/utils.js:98
>     process.nextTick(function() { throw err; });
>                                         ^
> MongoError: auth fails
>     at Function.MongoError.create (/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
>     at /Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:763:66
>     at Callbacks.emit (/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
>     at null.messageHandler (/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:243:23)
>     at Socket.<anonymous> (/Users/pat/sherlock/source/server/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
>     at Socket.emit (events.js:107:17)
>     at readableAddChunk (_stream_readable.js:163:16)
>     at Socket.Readable.push (_stream_readable.js:126:10)
>     at TCP.onread (net.js:529:20)
>
> and this error from mongo
>
> Fri Oct 23 17:06:27.315 [conn21] auth: couldn't find user localuser@source, source.system.users
> Fri Oct 23 17:06:27.315 [conn22]  authenticate db: source { authenticate: 1, user: "localuser", nonce: "976134d3c6dcf94a", key: "dd27985f93c506068fafbce130c86a75" }
> Fri Oct 23 17:06:27.315 [conn23]  authenticate db: source { authenticate: 1, user: "localuser", nonce: "33acfe74d59087a1", key: "bff0a7d70c838bb98249e0aa3f6c36ec" }
> Fri Oct 23 17:06:27.315 [conn22] auth: couldn't find user localuser@source, source.system.users
> Fri Oct 23 17:06:27.315 [conn23] auth: couldn't find user localuser@source, source.system.users
>
> Any idea on how to fix this? I would like to pull this in and test it as
> soon as possible
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/source/source/pull/12#issuecomment-150693041>.
>



-- 
All the best
Aleksandar Aleksandrov
*Title*: Project Leader & Software Developer
*Linked in*: http://www.linkedin.com/in/aleksandaraleksandrov
*Skype*: ta4kazzz
*Website:* http://ilovethismusic.codeplex.com

**Comment by source** [comment]
Okay that worked. I was able to launch both the ionic app and the node server no problem.

However - there was still no way to "signup with facebook" and many things seem broken.

In addition, when I made a new user and went to post an article, after I click "Publish article" it sent be back to the login screen with this error message in the console.

```
PUT http://localhost:8080/api/articles/562ba51ca66163b93c900058 401 (Unauthorized)
addController.js:90 Error when retreiving full article
```

When I then tried to login with my new credentials I received this error also
```
POST http://localhost:8080/api/users/connect?username=bob@bob.com&password=bob 401 (Unauthorized)(anonymous function) @ ionic.bundle.js:19341sendReq @ ionic.bundle.js:19160serverRequest @ ionic.bundle.js:18872processQueue @ ionic.bundle.js:23394(anonymous function) @ ionic.bundle.js:23410Scope.$eval @ ionic.bundle.js:24673Scope.$digest @ ionic.bundle.js:24484Scope.$apply @ ionic.bundle.js:24778(anonymous function) @ ionic.bundle.js:57513eventHandler @ ionic.bundle.js:12098triggerMouseEvent @ ionic.bundle.js:2865tapClick @ ionic.bundle.js:2854tapMouseUp @ ionic.bundle.js:2927
loginCtrl.js:46 undefined:undefined
```

Summary:
- I am still unable to login with my newly created credentials.
- The facebook button doesn't seem to trigger anything

* It also concerns me that I am able to see my unencrypted password in the URL parameter shown above. (in this case i choose the password "bob" and you can see it very clearly.

**Comment by ta4kazzz** [comment]
The facebook stuff i havent added yet as a pull request. For this you will
also need to setup an app on facebook and ad me as a developer there. I
will write you more detailed instructions.

About the other stuff i will investigate some more and see and fix any
issues on Monday.

**Pull request merged**
