### PR TITLE
Authorize fix and fb connect

### PR DESCRIPTION
**Pull request by ta4kazzz**
Included are login and register fixes and the fb connect

### CODE REVIEW

**Comment by source** [comment]
It looks like it is successfully writing users with salted passwords to the database and once I create a new user I am able to post articles. But after I logout and try to login in I am met with the following error in the console. 
```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
loginCtrl.js:46 Unauthorized:401
```

No error messages from the server or the DB

**Comment by ta4kazzz** [comment]
I tested all possible scenarios with registering and login, all seems to work fine on my end. Maybe do npm install on server, and clear cache in browser before testing ?

**Comment by source** [comment]
I tried both of those ideas but it still does not work. I will look at it again later today.

Is there any additional configurations that I must enact to the server, database, or client app? I still have localuser with a password of 123456 on my mongo - is this still necessary? 

The error message is very vague so I am unable to debug any further 

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
loginCtrl.js:46 Unauthorized:401
```

and on the server 

```
POST /api/users/connect 401 1.982 ms - -
```

**Comment by source** [comment]
Also - is this pull request (https://github.com/source/source/pull/12) need to be pulled in as well? I am not sure which PR to test.

Could you please provide a single Pull Request for me to checkout with all of the authentication fixes?

Thanks

**Comment by ta4kazzz** [comment]
AuthorizeFix_andFBConnect Has all the previous code. So just merge this one and you will be good to go. 

About the db settings I think you should use it maybe add a new password but always connect to db using password and username. 

About the error message, that one is custom from me on the server, when the user is not logged in he cannot call any server methods. You can see it in the helper.js file in node:

exports.isLoggedIn = function (req, res, next) {
        // if user is authenticated in the session, carry on
        if (req.session.userId) {
            return next();
        } else {
            res.status(401);
            res.send('You are not authorized to view this page');
        }
};

**Comment by source** [comment]
I found the problem. The login form still says "Email"  but after inspecting user.js in the server side code I see that it is asking for "username"

screen shot 2015-10-27 at 9 41 24 pm

Please correct the authentication so that the user logs in with their email.

**Comment by source** [comment]
It would also be nice to have proper error handling. An more specific error message that reads "there is no user with that email/username" would prevent this kind of confusion in the future

Thanks

**Pull request merged**
